import { c as create_ssr_component, d as add_attribute, f as each, e as escape } from "../../../chunks/ssr.js";
import "../../../chunks/api.js";
const _page_svelte_svelte_type_style_lang = "";
const css = {
  code: ".admin-header.svelte-a03gnf.svelte-a03gnf{text-align:center;margin-bottom:3rem}.admin-header.svelte-a03gnf h1.svelte-a03gnf{font-size:2.5rem;margin-bottom:0.5rem;color:#333}.admin-header.svelte-a03gnf p.svelte-a03gnf{color:#666;font-size:1.1rem}.admin-layout.svelte-a03gnf.svelte-a03gnf{display:grid;grid-template-columns:1fr 1fr;gap:2rem;align-items:start}.section-header.svelte-a03gnf.svelte-a03gnf{display:flex;justify-content:space-between;align-items:center;margin-bottom:2rem}.section-header.svelte-a03gnf h2.svelte-a03gnf{margin:0}.form-row.svelte-a03gnf.svelte-a03gnf{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.input-group.svelte-a03gnf.svelte-a03gnf{display:flex;gap:0.5rem;margin-bottom:0.5rem}.input-group.svelte-a03gnf .form-input.svelte-a03gnf{flex:1}.form-actions.svelte-a03gnf.svelte-a03gnf{display:flex;gap:1rem;margin-top:2rem}.products-table.svelte-a03gnf.svelte-a03gnf{display:flex;flex-direction:column;gap:1rem}.product-row.svelte-a03gnf.svelte-a03gnf{display:flex;justify-content:space-between;align-items:flex-start;padding:1rem;border:1px solid #e9ecef;border-radius:8px;transition:box-shadow 0.2s}.product-row.svelte-a03gnf.svelte-a03gnf:hover{box-shadow:0 2px 8px rgba(0,0,0,0.1)}.product-info.svelte-a03gnf.svelte-a03gnf{flex:1}.product-link.svelte-a03gnf.svelte-a03gnf{text-decoration:none;color:#007bff;font-weight:600}.product-link.svelte-a03gnf.svelte-a03gnf:hover{text-decoration:underline}.product-meta.svelte-a03gnf.svelte-a03gnf{color:#666;font-size:0.9rem;margin:0.5rem 0}.product-features.svelte-a03gnf.svelte-a03gnf{display:flex;flex-wrap:wrap;gap:0.25rem}.feature-tag.svelte-a03gnf.svelte-a03gnf{background:#e3f2fd;color:#1976d2;padding:0.2rem 0.4rem;border-radius:4px;font-size:0.8rem}.feature-tag.more.svelte-a03gnf.svelte-a03gnf{background:#f5f5f5;color:#666}.product-actions.svelte-a03gnf.svelte-a03gnf{display:flex;flex-direction:column;gap:0.5rem;min-width:100px}.empty-state.svelte-a03gnf.svelte-a03gnf{text-align:center;padding:2rem;color:#666}.message.success.svelte-a03gnf.svelte-a03gnf{background:#d4edda;color:#155724;border:1px solid #c3e6cb;border-radius:6px;padding:1rem;margin-bottom:2rem}.message.error.svelte-a03gnf.svelte-a03gnf{background:#f8d7da;color:#721c24;border:1px solid #f5c6cb;border-radius:6px;padding:1rem;margin-bottom:2rem}@media(max-width: 1024px){.admin-layout.svelte-a03gnf.svelte-a03gnf{grid-template-columns:1fr}.form-row.svelte-a03gnf.svelte-a03gnf{grid-template-columns:1fr}.product-row.svelte-a03gnf.svelte-a03gnf{flex-direction:column;gap:1rem}.product-actions.svelte-a03gnf.svelte-a03gnf{flex-direction:row;align-self:stretch}}@media(max-width: 768px){.section-header.svelte-a03gnf.svelte-a03gnf{flex-direction:column;gap:1rem;align-items:stretch}.form-actions.svelte-a03gnf.svelte-a03gnf{flex-direction:column}}",
  map: null
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let formData = {
    name: "",
    category: "",
    features: [""],
    keywords: [""],
    location: "",
    target_audience: ""
  };
  let products = [];
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-1ttg7ng_START -->${$$result.title = `<title>Admin - SEO Page Generator</title>`, ""}<meta name="description" content="Admin panel for creating and managing SEO-optimized product pages"><meta name="robots" content="noindex, nofollow"><!-- HEAD_svelte-1ttg7ng_END -->`, ""} <div class="container"><div class="admin-header svelte-a03gnf" data-svelte-h="svelte-1rpxry0"><h1 class="svelte-a03gnf">SEO Page Generator Admin</h1> <p class="svelte-a03gnf">Create AI-powered, SEO-optimized product pages that automatically appear in Google Search.</p></div> ${``} <div class="admin-layout svelte-a03gnf"> <section class="form-section card"><div class="section-header svelte-a03gnf"><h2 class="svelte-a03gnf" data-svelte-h="svelte-gpec8y">Create New Product Page</h2> <button type="button" class="btn btn-secondary btn-sm" data-svelte-h="svelte-qdjuoi">Load Example</button></div> <form><div class="form-row svelte-a03gnf"><div class="form-group"><label for="name" class="form-label" data-svelte-h="svelte-125kgel">Product Name *</label> <input type="text" id="name" class="form-input" placeholder="e.g., Colombian Dark Roast Coffee" required${add_attribute("value", formData.name, 0)}></div> <div class="form-group"><label for="category" class="form-label" data-svelte-h="svelte-11romv8">Category *</label> <input type="text" id="category" class="form-input" placeholder="e.g., Gourmet Coffee" required${add_attribute("value", formData.category, 0)}></div></div> <div class="form-group"><label class="form-label" data-svelte-h="svelte-1x5lh09">Features *</label> ${each(formData.features, (feature, index) => {
    return `<div class="input-group svelte-a03gnf"><input type="text" class="form-input svelte-a03gnf" placeholder="e.g., Single-Origin Excellence"${add_attribute("value", formData.features[index], 0)}> <button type="button" class="btn btn-danger btn-sm" ${formData.features.length <= 1 ? "disabled" : ""}>Remove</button> </div>`;
  })} <button type="button" class="btn btn-secondary btn-sm" data-svelte-h="svelte-u12p2p">+ Add Feature</button></div> <div class="form-group"><label class="form-label" data-svelte-h="svelte-10035oa">Keywords *</label> ${each(formData.keywords, (keyword, index) => {
    return `<div class="input-group svelte-a03gnf"><input type="text" class="form-input svelte-a03gnf" placeholder="e.g., dark roast coffee"${add_attribute("value", formData.keywords[index], 0)}> <button type="button" class="btn btn-danger btn-sm" ${formData.keywords.length <= 1 ? "disabled" : ""}>Remove</button> </div>`;
  })} <button type="button" class="btn btn-secondary btn-sm" data-svelte-h="svelte-pe78ix">+ Add Keyword</button></div> <div class="form-row svelte-a03gnf"><div class="form-group"><label for="location" class="form-label" data-svelte-h="svelte-1x0w8gm">Location *</label> <input type="text" id="location" class="form-input" placeholder="e.g., USA" required${add_attribute("value", formData.location, 0)}></div> <div class="form-group"><label for="target_audience" class="form-label" data-svelte-h="svelte-1jbrloj">Target Audience *</label> <input type="text" id="target_audience" class="form-input" placeholder="e.g., Coffee lovers who enjoy bold flavors" required${add_attribute("value", formData.target_audience, 0)}></div></div> <div class="form-actions svelte-a03gnf"><button type="submit" class="btn btn-primary" ${""}>${`🚀 Generate SEO Page`}</button> <button type="button" class="btn btn-secondary" data-svelte-h="svelte-3hpa3t">Clear Form</button></div></form></section>  <section class="products-section card"><h2>Existing Products (${escape(products.length)})</h2> ${products.length === 0 ? `<div class="empty-state svelte-a03gnf" data-svelte-h="svelte-1haio3p"><p>No products created yet. Use the form to create your first SEO page!</p></div>` : `<div class="products-table svelte-a03gnf">${each(products, (product) => {
    return `<div class="product-row svelte-a03gnf"><div class="product-info svelte-a03gnf"><h3><a href="${"/products/" + escape(product.slug, true)}" target="_blank" class="product-link svelte-a03gnf">${escape(product.name)} </a></h3> <p class="product-meta svelte-a03gnf">${escape(product.category)} • ${escape(product.location)} • 
                  Created ${escape(new Date(product.created_at).toLocaleDateString())}</p> <div class="product-features svelte-a03gnf">${each(product.features.slice(0, 3), (feature) => {
      return `<span class="feature-tag svelte-a03gnf">${escape(feature)}</span>`;
    })} ${product.features.length > 3 ? `<span class="feature-tag more svelte-a03gnf">+${escape(product.features.length - 3)} more</span>` : ``} </div></div> <div class="product-actions svelte-a03gnf"><a href="${"/products/" + escape(product.slug, true)}" target="_blank" class="btn btn-primary btn-sm">View Page</a> <button class="btn btn-danger btn-sm" data-svelte-h="svelte-ify02c">Delete
                </button></div> </div>`;
  })}</div>`}</section></div> </div>`;
});
export {
  Page as default
};
